package com.bizwink.persistence;

import com.bizwink.po.BaseContract;
import com.bizwink.po.BaseContractExample;

public interface BaseContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int countByExample(BaseContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int insert(BaseContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int insertSelective(BaseContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    BaseContract selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseContract record);
}