package com.bizwink.persistence;

import com.bizwink.po.BaseAttachment;
import com.bizwink.po.BaseAttachmentExample;

public interface BaseAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int countByExample(BaseAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int insert(BaseAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int insertSelective(BaseAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    BaseAttachment selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_attachment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseAttachment record);
}