package com.bizwink.persistence;

import com.bizwink.po.bhApplyCredit;
import com.bizwink.po.bhApplyCreditExample;

public interface bhApplyCreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int countByExample(bhApplyCreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int insert(bhApplyCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int insertSelective(bhApplyCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    bhApplyCredit selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(bhApplyCredit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bh_apply_credit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(bhApplyCredit record);
}