package com.bizwink.persistence;

import com.bizwink.po.BulletinNotice;
import com.bizwink.po.BulletinNoticeExample;
import com.bizwink.po.BulletinNoticeWithBLOBs;

public interface BulletinNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int countByExample(BulletinNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int insert(BulletinNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int insertSelective(BulletinNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    BulletinNoticeWithBLOBs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BulletinNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BulletinNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bulletin_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BulletinNotice record);
}