package com.bizwink.persistence;

import com.bizwink.po.ChangeNotice;
import com.bizwink.po.ChangeNoticeExample;
import com.bizwink.po.ChangeNoticeWithBLOBs;

public interface ChangeNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int countByExample(ChangeNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int insert(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int insertSelective(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    ChangeNoticeWithBLOBs selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ChangeNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table change_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChangeNotice record);
}