package com.bizwink.persistence;

import com.bizwink.po.WinResultsNotice;
import com.bizwink.po.WinResultsNoticeExample;
import com.bizwink.po.WinResultsNoticeKey;
import com.bizwink.po.WinResultsNoticeWithBLOBs;

public interface WinResultsNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int countByExample(WinResultsNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(WinResultsNoticeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int insert(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int insertSelective(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    WinResultsNoticeWithBLOBs selectByPrimaryKey(WinResultsNoticeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WinResultsNoticeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table win_results_notice
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WinResultsNotice record);
}