/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import com.bizwink.cms.security.*;
import com.bizwink.cms.util.*;

public class _header__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gbk");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("/webbuilder/index.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }
    String userid = authToken.getUserID();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    if (authToken != null && !userid.equalsIgnoreCase("admin")){
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print(("\u5f53\u524d\u7528\u6237"));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((userid));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print(("\u5f53\u524d\u7ad9\u70b9"));
    out.write('[');
    out.print((authToken.getSitename()));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    }
    out.write(_jsp_string6, 0, _jsp_string6.length);
    
                        if (userid.compareToIgnoreCase("admin") != 0) {
                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 1)) || SecurityCheck.hasPermission(authToken, 54)) {
                                //out.println("<td><a href=column/index.jsp?rightid=1 target=main><img src='images/lmsz.gif' border='0'></a></td>");
                                out.println("<td><a href=column/indexnew.jsp?rightid=1 target=main><img src='images/lmsz.gif' border='0'></a></td>");
                            }

                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 2)) || SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=template1/index.jsp?rightid=2 target=main><img src='images/mjgl.gif' border='0'></a></td>");
                            }

                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 3)) || SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=article1/index.jsp?rightid=3 target=main><img src='images/wzbj.gif' border='0'></a></td>");
                            }

                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 7)) || SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=articlemove/index.jsp?rightid=7 target=main><img src='images/ydwz.gif' border='0'></a></td>");
                            }

                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 5)) || SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=audit/index.jsp?rightid=5 target=main><img src='images/wzsh.gif' border='0'></a></td>");
                            }

                            if (((authToken != null) && SecurityCheck.hasPermission(authToken, 6)) || SecurityCheck.hasPermission(authToken, 54) || SecurityCheck.hasPermission(authToken, 8)) {
                                if (SecurityCheck.hasPermission(authToken, 6) || SecurityCheck.hasPermission(authToken, 54))
                                    out.println("<td><a href=publish/index.jsp?rightid=6 target=main><img src='images/wzfb.gif' border='0'></a></td>");
                                else
                                    out.println("<td><a href=publish/index.jsp?rightid=8 target=main><img src='images/wzfb.gif' border='0'></a></td>");
                            }

                            //if (((authToken != null) && SecurityCheck.hasPermission(authToken, 7)) || SecurityCheck.hasPermission(authToken, 54)) {
                            //out.println("<td><a href=toolkit/business/member/index2.jsp target=main><img src='images/ydwz.gif' border='0'></a></td>");
                            //}

                            //if (((authToken != null) && SecurityCheck.hasPermission(authToken, 5)) || SecurityCheck.hasPermission(authToken, 54)) {
                            //out.println("<td><a href=toolkit/business/order/index.jsp target=main><img src='images/wzsh.gif' border='0'></a></td>");
                            //}

                            if ((authToken != null) && !SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=member/changePass.jsp target=main><img src='images/xgma.gif' border='0'></a></td>");
                            }

                            if ((authToken != null) && SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=member/index.jsp target=main><img src='images/xtsz.gif' border='0'></a></td>");
                            }

                            //if ((authToken != null) && SecurityCheck.hasPermission(authToken, 54)) {
                            //    out.println("<td><a href=toolkit/business/index1.jsp target=_parent><img src='images/dzsw.jpg' border='0'></a></td>");
                            //}

                            if (authToken != null && SecurityCheck.hasPermission(authToken, 54)) {
                                out.println("<td><a href=toolkit/index.jsp target=main><img src='images/gjx.gif' border='0'></a></td>");
                            }
                        } else {
                            out.println("<td><a href=member/admin_index.jsp target=main><img src='images/yhgl.gif' border='0'></a></td>");
                            out.println("<td><a href=member/siteManage.jsp target=main><img src='images/zdgl.gif' border='0'></a></td>");
                            out.println("<td><a href=adminx/autoPub.jsp target=main><img src='images/swgl.gif' border='0'></a></td>");
                            out.println("<td><a href=program/pmanager.jsp target=main><img src='images/join2009572.jpg' border='0'></a></td>");
                            out.println("<td><a href=member/listStyle.jsp target=main><img src='images/yswj.gif' border='0'></a></td>");
                            out.println("<td><a href=movecolumn/index.jsp target=main><img src='images/lmqy.gif' border='0'></a></td>");
                            out.println("<td><a href=member/logManage.jsp target=main><img src='images/gzl.gif' border='0'></a></td>");
                            //out.println("<td><a href=joincompany/list.jsp target=main>\u52a0\u76df\u5546\u7ba1\u7406</a></td>");
                            //out.println("<td><a href=navigator/listNavigator.jsp target=main>\u5bfc\u822a\u6761\u7ba1\u7406</a></td>");
                        }
                    
    out.write(_jsp_string7, 0, _jsp_string7.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 3236584570990572425L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string6;
  private final static char []_jsp_string5;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  static {
    _jsp_string3 = " [".toCharArray();
    _jsp_string6 = "\r\n    </script>\r\n</head>\r\n\r\n<body>\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#FFAE08\">\r\n    <tr bgcolor=\"#FFAE08\" height=\"60\">\r\n        <td width=\"2%\">&nbsp;</td>\r\n        <td width=\"85%\">\r\n            <table width=\"620\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n                <tr>\r\n                    ".toCharArray();
    _jsp_string5 = "]\";\r\n        ".toCharArray();
    _jsp_string7 = "\r\n                </tr>\r\n            </table>\r\n        </td>\r\n        <td width=\"13%\">\r\n            <a href=\"help/index.htm\" target=_blank><img src=\"images/help.gif\" border=\"0\"></a>&nbsp;\r\n            <a href=\"javascript:go();\"><img src=\"images/exit.gif\" border=\"0\"></a>\r\n        </td>\r\n    </tr>\r\n</table>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n    <link rel=stylesheet type=text/css href=\"style/global.css\">\r\n    <link rel=stylesheet type=text/css href=\"style/cms.css\">\r\n\r\n    <script language=javascript>\r\n        function go()\r\n        {\r\n            parent.document.location = \"exit.jsp\";\r\n        }\r\n\r\n        function publish()\r\n        {\r\n            window.open(\"autoPublish/publish.jsp\", \"SelectRight\", \"top=10,left=10,width=190,height=80,resizable=no,scrollbars=no,status=no,toolbar=no,menubar=no,location=no\");\r\n        }\r\n\r\n        ".toCharArray();
    _jsp_string2 = "\r\n        window.status = \"".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string4 = "]    ".toCharArray();
  }
}
