/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.bizwink.cms.util.*;
import com.bizwink.cms.audit.*;
import com.bizwink.cms.security.*;

public class _main__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gbk");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("../login.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }

    IAuditManager auditMgr = AuditPeer.getInstance();
    String userID = authToken.getUserID();
    int siteID = authToken.getSiteID();

    int backCount = 0;
    int auditCount = 0;
    if (!userID.equalsIgnoreCase("admin"))
    {
        //\u9000\u7a3f
        List backList = auditMgr.getBack_Articles(userID);
        backCount = backList.size();

        //\u5ba1\u6838
        String user_ID = "[" + userID + "]";
        List auditList = auditMgr.getArticles_NeedAudit(user_ID, siteID);
        auditCount = auditList.size();
    }

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((backCount));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((auditCount));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((auditCount));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    
    String[][] titlebars = {
            { "\u9996\u9875", "" }
    };
    String[][] operations=null;

    out.write(_jsp_string5, 0, _jsp_string5.length);
    
if( titlebars != null ) {
    out.println("<table class=line width=100% border=0 cellspacing=0 cellpadding=0>");
    out.println("<tr bgcolor=#003366><td height=2 colspan=2></td></tr>");
    out.println("<tr><td width=50% class=line>");
    int i=0;
    while( titlebars.length > 1 && i < (titlebars.length-1) ) {
	     out.println("<a href=\"javascript:parent.document.location='index.jsp'\" target=_blank>");
	     out.println(titlebars[i][0] +"</a>&gt;");
	     i++;
    }
    if( titlebars.length >= 1 ) {
        out.println(titlebars[i][0]);
    }
    out.println("</td><td width=50% align=right class=line>");
    if (operations != null) {
        i=0;
        while( operations.length > 0 && i < operations.length ) {
            if(operations[i][1] != "")
                out.println("<a href="+ operations[i][1] +">"+ operations[i][0] +"</a>&nbsp;");
            else
                out.println(operations[i][0]);
	    i++;
        }
    }
    out.println("</td></tr>");
    out.println("<tr bgcolor=#003366><td colspan=2 height=2></td>");
    out.println("</tr></table>");
}

    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("main.jsp"), 637333246061952205L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("inc/titlebar.jsp"), 1416346678249567651L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = " != 0) {\r\n            if (".toCharArray();
    _jsp_string6 = "\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string4 = " != 0)\r\n                param = 2;\r\n            }\r\n\r\n            if (param != 0)\r\n            {\r\n                window.open(\"inc/note.jsp?param=\"+param,\"note\",\"width=400,height=400,left=200,top=150,scrollbars=yes\");\r\n            }\r\n        } */\r\n\r\n        function MM_openBrWindow(theURL,winName,features) { //v2.0\r\n            window.open(theURL,winName,features);\r\n        }\r\n\r\n        function post() {\r\n            //window.open(\"openemail.jsp\",\"openemail\",\"width=800,height=600,left=20,top=10,scrollbars=yes resize=yes\");\r\n        }\r\n        //-->\r\n    </script>\r\n\r\n</head>\r\n\r\n<BODY LINK=#000099 ALINK=#cc0000 VLINK=#000099 TOMARGIN=8 onload=\"javascript:post();\">\r\n<!--body link=#000099 alink=#cc0000 vlink=#000099 TOMARGIN=8-->\r\n<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n    <tr bgcolor=\"#000000\">\r\n        <td height=\"2\"></td>\r\n    </tr>\r\n</table>\r\n\r\n".toCharArray();
    _jsp_string5 = "\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n    <link rel=stylesheet type=text/css href=style/global.css>\r\n\r\n    <script language=\"JavaScript\">\r\n        <!--\r\n        /*function window_open()\r\n        {\r\n            //1:\u6709\u9000\u7a3f\r\n            //2:\u6709\u5ba1\u6838\r\n            //3:\u90fd\u6709\r\n            //0:\u90fd\u65e0\r\n            var param = 0;\r\n\r\n        if (".toCharArray();
    _jsp_string3 = " != 0)\r\n            param = 3;\r\n        else\r\n            param = 1;\r\n        }\r\n        else\r\n            {\r\n                if (".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
