package com.bizwink.basic.code.persistence;

import com.bizwink.basic.code.po.NameValueVode;
import com.bizwink.basic.code.po.NameValueVodeExample;
import com.bizwink.basic.code.po.NameValueVodeKey;

public interface NameValueVodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int countByExample(NameValueVodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(NameValueVodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int insert(NameValueVode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int insertSelective(NameValueVode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    NameValueVode selectByPrimaryKey(NameValueVodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NameValueVode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_namevaluecode
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NameValueVode record);
}